export const ROUTES = {
  ONBOARDING: 'ONBOARDING',
  AUTH: 'AUTH',
  MAIN: 'MAIN',
  SIGN_IN: 'SIGN_IN',
  EMAIL_INPUT: 'EMAIL_INPUT',
  OTP: 'OTP',
  TABS: 'TABS',
  HOME: 'HOME',
  PROFILE: 'PROFILE',
} as const