export const ROUTES = {
  ONBOARDING: 'ONBOARDING',
  AUTH: 'AUTH',
  MAIN: 'MAIN',
  SIGN_IN: 'SIGN_IN',
  EMAIL_INPUT: 'EMAIL_INPUT',
  OTP: 'OTP',
  TABS: 'TABS',
  NEARBY_HOTEL: 'NEARBY_HOTEL',
  SEARCH: 'SEARCH',
  HOTEL_DETAIL: 'HOTEL_DETAIL',
  HOME: 'HOME',
  MY_BOOKING: 'MY_BOOKING',
  MESSAGE: 'MESSAGE',
  PROFILE: 'PROFILE'
} as const